
package org.fing.middleware.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServicioRecepcionPagos", targetNamespace = "http://services.middleware.fing.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioRecepcionPagos {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.fing.middleware.services.ConfirmacionTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recepcionPagos", targetNamespace = "http://services.middleware.fing.org/", className = "org.fing.middleware.services.RecepcionPagos")
    @ResponseWrapper(localName = "recepcionPagosResponse", targetNamespace = "http://services.middleware.fing.org/", className = "org.fing.middleware.services.RecepcionPagosResponse")
    public ConfirmacionTransaccion recepcionPagos(
        @WebParam(name = "arg0", targetNamespace = "")
        TransaccionPago arg0);

}
